name : Deployment

on:
  push:
    branches:
      - master

jobs:
  create-deployment-artifact:
    name: Create Deployment Artifact
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Configure PHP 8.0
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --no-interaction --prefer-dist
          composer update --no-dev --no-interaction --prefer-dist

