name: Deployment

on:
  push:
    branches:
      - master

jobs:
  create-deployment-artifact:
    name: Create Deployment Artifact
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3

      - name : Compile CSS and JavaScript
        run: |
          npm install
          npm run prod